In [1]:
my_list = list(range(1000000))
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 750 ms
Wall time: 755 ms


In [1]:
import numpy as np
my_arr = np.arange(1000000)
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: total: 15.6 ms
Wall time: 12.9 ms


In [2]:
import numpy as np
data = np.random.randn(2, 3)
data

array([[ 1.52601375, -0.55634438, -0.53828479],
       [-0.43046967, -0.94416143, -0.02807502]])

In [3]:
data * 2

array([[ 3.0520275 , -1.11268876, -1.07656959],
       [-0.86093934, -1.88832286, -0.05615005]])

In [4]:
data + data

array([[ 3.0520275 , -1.11268876, -1.07656959],
       [-0.86093934, -1.88832286, -0.05615005]])

In [5]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)
print(arr1.ndim)
print(arr1.dtype)

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)

[6.  7.5 8.  0.  1. ]
1
float64
[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int32


In [6]:
import numpy as np
np.zeros(10)
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
