# Python overview

In [ ]:
import sys

print(1, 2, 3, 4, sep='*', end=' END\n', file=sys.stdout, flush=True)
# change sys.stdout to file object to write to file

In [10]:
# None Type
# None
a = None
print("Value of a:", a, "Type:", type(a))

# Numeric Types
# Integer
x = 10
print("Value of x:", x, "Type:", type(x))

# Float
y = 20.5
print("Value of y:", y, "Type:", type(y))

# Complex
z = 2 + 1j
print("Value of z:", z, "Type:", type(z))
print("Value of complex():", complex(), "Type:", type(complex()))
print("Value of complex('3-4j):", complex('3-4j'), "Type:", type(complex(complex('3-4j'))))
# print("Value of complex('5 + 6j'):", complex('5 + 6j'), "Type:", type(complex('5 + 6j'))) # ValueError

# Boolean
is_true = True
print("Value of is_true:", is_true, "Type:", type(is_true))

# Sequence Types
# String (immutable) -> create new string when modified
s = "Hello, world!"
print("Value of s:", s, "Type:", type(s))

# List 
list1 = [1, 2, 3, 4, 5]
print("Value of list1:", list1, "Type:", type(list1), "Length:", len(list1))

# Tuple (immutable list)
tuple1 = (1, 2, 3, 4, 5)
print("Value of tuple1:", tuple1, "Type:", type(tuple1), "Length:", len(tuple1))

# Range (immutable list of integers)
r = range(1, 10)
print("Value of r:", r, "Type:", type(r))

# Mapping Types
# Dictionary 
dict1 = {"name": "John", "age": 30}
print("Value of dict1:", dict1, "Type:", type(dict1))

# Set 
set1 = {1, 2, 3, 4, 5}
print("Value of set1:", set1, "Type:", type(set1), "Length:", len(set1))

# Frozenset (immutable set)
fs = frozenset([1, 2, 3, 4, 5])
print("Value of fs:", fs, "Type:", type(fs))

Value of a: None Type: <class 'NoneType'>
Value of x: 10 Type: <class 'int'>
Value of y: 20.5 Type: <class 'float'>
Value of z: (2+1j) Type: <class 'complex'>
Value of complex(): 0j Type: <class 'complex'>
Value of complex('3-4j): (3-4j) Type: <class 'complex'>
Value of is_true: True Type: <class 'bool'>
Value of s: Hello, world! Type: <class 'str'>
Value of list1: [1, 2, 3, 4, 5] Type: <class 'list'> Length: 5
Value of tuple1: (1, 2, 3, 4, 5) Type: <class 'tuple'> Length: 5
Value of r: range(1, 10) Type: <class 'range'>
Value of dict1: {'name': 'John', 'age': 30} Type: <class 'dict'>
Value of set1: {1, 2, 3, 4, 5} Type: <class 'set'> Length: 5
Value of fs: frozenset({1, 2, 3, 4, 5}) Type: <class 'frozenset'>


In [11]:
# addition or concatenation
a = 5 + 3  # a is 8
print(a)
b = "Hello " + "World"  # b is "Hello World"
print(b)

# subtraction
a = 5 - 3  # a is 2
print(a)

# multiplication or repetition
a = 5 * 3  # a is 15
print(a)
b = "Hello " * 3  # b is "Hello Hello Hello "
print(b)

# division
a = 5 / 3  # a is approximately 1.66667
print(a)

# floor division
a = 5 // 3  # a is 1
print(a)

# modulus
a = 5 % 3  # a is 2
print(a)

# exponentiation
a = 5 ** 3  # a is 125
print(a)

# compound assignment
a = 5
a += 3  # a is 8
print(a)
a*=3  # a is 24
print(a)
a//=5  # a is 4
print(a)
a**=3  # a is 64
print(a)

8
Hello World
2
15
Hello Hello Hello 
1.6666666666666667
1
2
125
8
24
4
64


In [17]:
# Implicit cast between numeric types
a = 5
b = 3.0
c = a + b  # c is 8.0
print(c)
d = a / b  # d is 1.66667
print(d)
e = 3 + 4j
f = e + d  # f is 4.66667 + 4j
print(f)
g = 5 + 6.78j
h = e + g  # h is 8 + 10.78j
print(h)


8.0
1.6666666666666667
(4.666666666666667+4j)
(8+10.780000000000001j)


In [19]:
# Other datatype requires explicit cast
age = 18
print("Tôi" + str(age) + "tuổi")

Tôi18tuổi


In [13]:
x, y, z = map(int, input().split()) # default separator is space
print(x, y, z)

a, b, c = map(int, input().split(',')) # separator is comma
print(a, b, c)

3 4 5
6 7 8


In [2]:
age = 15
status = ('teenager' if age > 12 and age < 20 else 'not teenager')
print(status)

teenager


In [3]:
# example of bitwise operators
a = 60            # 60 = 0011 1100
b = 13            # 13 = 0000 1101

# Bitwise AND
c = a & b        # 12 = 0000 1100
print("Bitwise AND:", c)

# Bitwise OR
c = a | b        # 61 = 0011 1101
print("Bitwise OR:", c)

# Bitwise XOR (diff = 1, no diff = 0)
c = a ^ b        # 49 = 0011 0001
print("Bitwise XOR:", c)

# Bitwise NOT
c = ~a           # -61 = 1100 0011
print("Bitwise NOT:", c)

# Bitwise Left Shift
c = a << 2       # 240 = 1111 0000
print("Bitwise Left Shift:", c)

# Bitwise Right Shift
c = a >> 2       # 15 = 0000 1111
print("Bitwise Right Shift:", c)

Bitwise AND: 12
Bitwise OR: 61
Bitwise XOR: 49
Bitwise NOT: -61
Bitwise Left Shift: 240
Bitwise Right Shift: 15


In [1]:
x = 2.01
print(x*100)

200.99999999999997


In [9]:
for _ in range(0, 10, 2): # range(start, stop, step) just like list slice [start:stop:step], stop is not reached
    print('.', end='')
    print()

.
.
.
.
.


In [8]:
num = int(input('Enter a number to check for: '))
for i in range(0, 6):
    print(i, ' ', end='')
else: # else block is executed when loop is not terminated by break
    print()
    print('All iterations successful')

0  1  2  3  4  5  
All iterations successful


In [12]:
str1 = '0123456789'
print(str1[1:5]) # 01234, default step = 1
print(str1[5:]) # 56789
print(str1[:5]) # 01234
print(str1[5:-1]) # 5678
print(str1[-1:-5]) # empty string
print(str1[-1:-5:-1]) # 9876, step = -1 means reverse

1234
56789
01234
5678

9876


In [18]:
print("""Tháp mười đẹp nhất bông sen
 Việt Nam đẹp nhất có tên Bác Hồ""")

name = "Trà"
age = 18
print(f"{name} năm nay {age} tuổi. Hỏi bạn trai của {name} bao nhiêu tuổi?")
print("{0} năm nay {1} tuổi. Hỏi bạn trai của {0} bao nhiêu tuổi?".format(name, age))
x = 3.14159
print('%.2f' % x)
print("{:.2f}".format(x)) 
print(f"{x:.2f}")

Tháp mười đẹp nhất bông sen
 Việt Nam đẹp nhất có tên Bác Hồ
Trà năm nay 18 tuổi. Hỏi bạn trai của Trà bao nhiêu tuổi?
Trà năm nay 18 tuổi. Hỏi bạn trai của Trà bao nhiêu tuổi?
3.14
3.14
3.14


In [22]:
#examples of common string methods
s = "hello world"
print(s.upper())
print(s.lower())
print(s.replace('l', 'L'))
print(s.split(' '))
print(s.count('l'))
print(s.find('l')) # return index of first occurence, -1 if not found
print(ord('a')) # 97
print(chr(97)) # a

HELLO WORLD
hello world
heLLo worLd
['hello', 'world']
3
2
97
a


In [29]:
list1 = [1, 2, 3, 4, 5]
list1[1:3] = [6, 7, 8, 9, 10] # replace 2, 3 by 6, 7, 8
print(list1)
del list1[1:3] # delete 6, 7
print(list1)

fruits = ["Táo", "Nho", "Lê"]
fruits_copy = fruits
fruits_clone = fruits[:] 
fruits_copy[0] = "Chôm chôm"
print(fruits)           
print(fruits_copy) 
print(fruits_clone)

odd_square = [x ** 2 for x in range(1, 11) if x % 2 == 1]
print (odd_square)

[1, 6, 7, 8, 9, 10, 4, 5]
[1, 8, 9, 10, 4, 5]
['Chôm chôm', 'Nho', 'Lê']
['Chôm chôm', 'Nho', 'Lê']
['Táo', 'Nho', 'Lê']
[1, 9, 25, 49, 81]


In [36]:
max = 100
def print_max():
    global max
    max = max + 1
    print(max)
print_max()
print(max)

def outer():
    x = "local"
    
    def inner():
        nonlocal x
        x = "nonlocal"
        print("inner:", x)
    
    inner()
    print("outer:", x)

outer()

101
101
inner: nonlocal
outer: nonlocal


In [1]:
_abc = 12
print(_abc)
1a = 13 # count 1a as a number -> error
print(1a)

SyntaxError: invalid decimal literal (3382225073.py, line 3)

In [3]:
import sys

print(1, 2, 3, 4, sep='*', end=' END\n', file=sys.stdout, flush=True)
# change sys.stdout to file object to write to file

1*2*3*4 END


In [6]:
numbers = [2, 3, 4]
print(numbers)

[2, 3, 4]


In [8]:
for x in range(0.5, 5.5, 0.5): # only range of integers
    print(x)

TypeError: 'float' object cannot be interpreted as an integer

In [9]:
sampleList = ["Jon", "Kelly", "Jessa"]
sampleList.append(2, "Scott") # append takes only one argument
print(sampleList)

TypeError: list.append() takes exactly one argument (2 given)

In [12]:
listOne = [20, 40, 60, 80]
listTwo = [20, 40, 60, 80]

print(listOne == listTwo)
print(listOne is listTwo)

True
False


In [14]:
def printHello():
    print("Hello") 
    
a = printHello()
# print(a)

Hello


In [17]:
class Point:
    def __init__(self, x = 0, y = 0):
        self.x = x+1
        self.y = y+1

class ColorPoint(Point): # subclass of Point
    def __init__(self, x = 0, y = 0, color = "black"):
        super().__init__(x, y)
        self.color = color

cp = ColorPoint(1, 2, 'white')
print(cp.x, cp.y, cp.color)

2 3 white


In [ ]:
class Foo:
    pass # use pass to create an empty class without error
class Hoo(Foo): # class Hoo inherits from class Foo
    pass # use pass to create an empty class without error

In [22]:
class A:
    def __init__(self):
        self.a = 1
        self._b = 1
    def getB(self):
        return self._b

obj = A()
obj.a = 45
obj._b = 45
print(obj.a)
print(obj._b)

45
45


In [18]:
try:
    # some code that might raise an exception
    x = 1 / 0
except ZeroDivisionError:
    print("Divided by zero!")
finally:
    print("This is always executed.")

Divided by zero!
This is always executed.


In [ ]:
with open('myfile.txt', 'a') as f: # 'a' is for append - write only, "with" has exception handling
    f.read()
    f.write('Hello, World!\n')

In [27]:
import os
os.listdir() # list all files and folders in the current directory, not child directories

['CK-practice.ipynb']

In Python, the open function can be used with several modes:

- 'r': Read - Default - If not exist ->FileNotFoundError
- 'w': Write - If file exists, all existing data will be deleted - Create if not exist
- 'a': Append - Write to the end of the file without deleting any existing data - Create if not exist
- 'x': Exclusive creation mode - Allows you to create a new file - If file already exists, opening it in this mode will raise a FileExistsError.
- 'b': Binary - Allows you to read/write binary data
- 't': Text - Default - Allows you to read/write string data.

In [31]:
def printHello():
    print("Hello")
a = printHello()

Hello


In [32]:
def outerFunction(): #12
    global a
    a = 20
def innerFunction():
    global a
    a = 30
print('a =', a)
a = 10
outerFunction()
print('a =', a)

a = None
a = 20


In [35]:
f = open('test.txt', 'r', encoding = 'utf-8')
f.read(12)

'sa;sadhf sdj'

- Exception is error occured in runtime (Runtime Error)
- So, RuntimeError is a type of exception that is raised when an error is detected that doesn’t fall in any of the other categories.

In [38]:
myList = [1, 5, 5, 5, 5, 1]
max = myList[0]
indexOfMax = 0
for i in range(1, len(myList)):
    if myList[i] > max: 
        max = myList[i]
        indexOfMax = i
print(indexOfMax)

1


In [39]:
x = 100
y = 50
z = 69
print(x and z and y)

50


In [ ]:
for i in range(10):
    if i == 5:
        break
    else:
        print(i)
print("Here")


In [41]:
string = "my name is x"
for i in string:
    print (i, end=", ")

m, y,  , n, a, m, e,  , i, s,  , x, 

In [42]:
i = 0
x = 0 
while i < 10:
    if i % 2 == 0:
        x += 1
    i += 1
print(x)

5


In [ ]:
def f(value): 
    while True:
        value = (yield value)

a = f(10)
print(next(a))
print(next(a))
print(a.send(20))

In [43]:
x = 1
y = "2"
z = 3
sum = 0
for i in (x, y, z):
    if isinstance(i, int):
        sum += i
print(sum)

4


In [47]:
print(round(4.576))
print(round(4.576, 2))
print(round(4.576, 3))

5
4.58
4.576


In [48]:
pow(2, 3, 4)

0

In [51]:
print(all([2,4,0,6]))
print(any([2>8, 4>2, 1>2]))

False


TypeError: all() takes exactly one argument (3 given)

In [ ]:
print(all(3,0,4.2))

In [ ]:
sum(2,4,6)
sum([1,2,3])

In [52]:
min(max(False,-3,-4), 2,7)

TypeError: 'int' object is not callable

In [53]:
complex()
complex(‘2-3j’) là hợp lệ còn complex(‘2 – 3j’) sai cú pháp

0j

In [54]:
divmod(5,3)
divmod(10.5,5)
divmod(2.4,1.2)

(1, 2)

In [ ]:
list(enumerate([2, 3]))

In [55]:
list(reversed([2, 3, 4]))

[4, 3, 2]

In [56]:
float(' -12345\n')
float('-infinity')
float('inf')

-12345.0

In [58]:
ord(65)
ord('A')

TypeError: ord() expected string of length 1, but int found

In [59]:
hex(15)

'0xf'

In [ ]:
oct(7)
oct('7')

In [61]:
x = 50
def func(x):
    print('Giá trị của x là', x)
    x = 2
print('Giá trị của x được thay đổi thành', x)
func(x)
print('Giá trị hiện tại của x là', x)

Giá trị của x được thay đổi thành 50
Giá trị của x là 50
Giá trị hiện tại của x là 50


In [64]:
x = 50
def func():
    global x
    print('Giá trị của x là', x)
    x = 2
print('Giá trị của x được thay đổi thành', x)
func()
print('Giá trị hiện tại của x là', x)

Giá trị của x được thay đổi thành 50
Giá trị của x là 50
Giá trị hiện tại của x là 2


In [ ]:
# python docstring
def add_numbers(a, b):
    """
    This function adds two numbers and returns the result.

    Parameters:
    a (int): The first number
    b (int): The second number

    Returns:
    int: The sum of a and b
    """
    return a + b

In [68]:
L = "[5:2,10:[1,2]"
type(L)

str

# Logger

In [ ]:
import logging
logging.basicConfig(format='%(asctime)s %(message)s',
level=logging.DEBUG)
logger = logging.getLogger(__name__)

logger.debug('This is to help with debugging') 
logger.info('This is just for information') 
logger.warning('This is a warning!') 
logger.error('This should be used with something unexpected') 
logger.critical('Something serious') 

# Numpy

In [40]:
import numpy as np

# 3x3 matrix
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("3x3 matrix:\n", arr)

print(arr[:2, 1:]) # arr[row, column]

3x3 matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
